uridine_mod_paths = {'U_to_D': ['U'],
                     'U_to_Um': ['U'],
                     'U_to_Y': ['U'],
                     'U_to_acp3U': ['U'],
                     'U_to_cmnm5U': ['U'],
                     'U_to_ho5U': ['U'],
                     'U_to_m3U': ['U'],
                     'U_to_m5U': ['U'],
                     'U_to_nm5U': ['U'],
                     'U_to_s2U': ['U'],
                     'U_to_s4U': ['U'],
                     'ho5U_to_mo5U' : ['U_to_ho5U'],
                     's2U_to_cmnm5s2U' : ['U_to_s2U'],
                     's2U_to_se2U' : ['U_to_s2U'],
                     's2U_to_ges2U' : ['U_to_s2U'],
                     'cmnm5U_to_cmnm5s2U' : ['U_to_cmnm5U'],
                     's2U_to_nm5s2U' : ['U_to_s2U'],
                     'ho5U_to_cmo5U' : ['U_to_ho5U'],
                     'nm5U_to_mnm5U' : ['U_to_nm5U', 'cmnm5U_to_nm5U'],
                     'Um_to_cmnm5Um' : [ 'U_to_Um'],
                     'cmnm5U_to_cmnm5Um' : ['U_to_cmnm5U'],
                     'cmnm5U_to_nm5U' : ['U_to_cmnm5U'],
                     'se2U_to_nm5se2U' : ['s2U_to_se2U'],
                     'nm5s2U_to_mnm5s2U' : ['s2U_to_nm5s2U','cmnm5s2U_to_nm5s2U'],
                     'nm5s2U_to_nm5se2U' : ['s2U_to_nm5s2U','cmnm5s2U_to_nm5s2U'],
                     'mnm5U_to_mnm5s2U' : ['nm5U_to_mnm5U'],
                     'mnm5s2U_to_mnm5se2U' :['nm5s2U_to_mnm5s2U','mnm5U_to_mnm5s2U'],
                     'nm5se2U_to_mnm5se2U' : ['cmnm5se2U_to_nm5se2U',  'se2U_to_nm5se2U' ,'nm5s2U_to_nm5se2U' ],
                     'cmnm5s2U_to_nm5s2U' : ['s2U_to_cmnm5s2U','cmnm5U_to_cmnm5s2U'],
                     'se2U_to_cmnm5se2U' : ['s2U_to_se2U'],
                     'Y_to_m3Y' : ['U_to_Y'],
                     'cmnm5se2U_to_nm5se2U' : ['se2U_to_cmnm5se2U','cmnm5s2U_to_cmnm5se2U'], 
                     'mnm5s2U_to_mnm5ges2U' : ['nm5s2U_to_mnm5s2U','mnm5U_to_mnm5s2U'],
                     'cmnm5s2U_to_cmnm5se2U' :['s2U_to_cmnm5s2U','cmnm5U_to_cmnm5s2U']
                    }

guanine_mods_path = {'QtRNA_to_gluQtRNA' : ['oQtRNA_to_QtRNA'],
                     'G_to_m1G' : ['G'],
                     'G_to_Gm' : ['G'],
                     'G_to_m2G' : ['G'],
                     'oQtRNA_to_QtRNA' : [ 'preq1tRNA_to_oQtRNA'],
                     'preq1tRNA_to_oQtRNA' : ['G_to_preq1tRNA'],
                     'G_to_preq1tRNA' : ['G'], 
                     'G_to_m7G' :['G'] 
                     }

cytidine_mods_path = {'C_to_s2C' : ['C'] ,
                      'C_to_k2C': ['C'] ,
                      'm4Cm_to_m44Cm': ['Cm_to_m4Cm', 'm4C_to_m4Cm'],
                      'C_to_m5C': ['C'] ,
                      'm4C_to_m44C': ['C_to_m4C'],
                      'C_to_m4C': ['C'] ,
                      'C_to_Cm': ['C'] ,
                      'Cm_to_m4Cm': ['C_to_Cm'],
                      'C_to_ac4C': ['C'] ,
                      'm4C_to_m4Cm': ['C_to_m4C'] 
                     }

adenine_mods_path = {'A_to_m2A' :['A'],
                     'i6A_to_ms2i6A' : ['A_to_i6A'],
                     't6A_to_m6t6A' : ['A_to_t6A'],
                     'm6A_to_m66A' :['A_to_m6A'],
                     'A_to_m1A':['A'],
                     'A_to_i6A':['A'],
                     'A_to_I':['A'],
                     'A_to_m6A':['A'],
                     'A_to_t6A':['A'],
                     't6A_to_ct6A' : ['A_to_t6A']
                    }



#trying something new
uridine_mod_paths = {'U_to_D' : {'upstream_rxns' : ['U'],
                                       'positions' : []},
                     'U_to_Um' : {'upstream_rxns' : ['U'],
                                       'positions' : ['']},
                     'U_to_Y' : {'upstream_rxns' : ['U'],
                                       'positions' : ['']},
                     'U_to_acp3U' : {'upstream_rxns' : ['U'],
                                       'positions' : ['']},
                     'U_to_cmnm5U' : {'upstream_rxns' : ['U'],
                                       'positions' : ['']},
                     'U_to_ho5U' : {'upstream_rxns' : ['U'],
                                       'positions' : ['']},
                     'U_to_m3U' : {'upstream_rxns' : ['U'],
                                       'positions' : ['']},
                     'U_to_m5U' : {'upstream_rxns' : ['U'],
                                       'positions' : ['']},
                     'U_to_nm5U' : {'upstream_rxns' : ['U'],
                                       'positions' : ['']},
                     'U_to_s2U' : {'upstream_rxns' : ['U'],
                                       'positions' : ['']},
                     'U_to_s4U' : {'upstream_rxns' : ['U'],
                                       'positions' : ['']},
                     'ho5U_to_mo5U' : {'upstream_rxns' : ['U_to_ho5U'],
                                       'positions' : ['']},
                     's2U_to_nm5s2U' : {'upstream_rxns' : ['U_to_s2U'],
                                       'positions' : ['']},
                     'cmnm5U_to_cmnm5s2U' : {'upstream_rxns' : ['U_to_cmnm5U'],
                                       'positions' : ['']},
                     's2U_to_ges2U' : {'upstream_rxns' : ['U_to_s2U'],
                                       'positions' : ['']},
                     's2U_to_se2U' : {'upstream_rxns' : ['U_to_s2U'],
                                       'positions' : ['']},
                     's2U_to_cmnm5s2U' : {'upstream_rxns' : ['U_to_s2U'],
                                       'positions' : ['']},
                     'cmnm5s2U_to_cmnm5se2U' : {'upstream_rxns' : ['s2U_to_cmnm5s2U','cmnm5U_to_cmnm5s2U'],
                                       'positions' : ['']},
                     'mnm5s2U_to_mnm5ges2U' : {'upstream_rxns' : ['nm5s2U_to_mnm5s2U','mnm5U_to_mnm5s2U'],
                                       'positions' : ['']},
                     'cmnm5se2U_to_nm5se2U' : {'upstream_rxns' : ['se2U_to_cmnm5se2U','cmnm5s2U_to_cmnm5se2U'],
                                       'positions' : ['']},
                     'Y_to_m3Y' : {'upstream_rxns' : ['U_to_Y'],
                                       'positions' : ['']},
                     'se2U_to_cmnm5se2U' : {'upstream_rxns' : ['s2U_to_se2U'],
                                       'positions' : ['']},
                     'cmnm5s2U_to_nm5s2U' : {'upstream_rxns' : ['s2U_to_cmnm5s2U','cmnm5U_to_cmnm5s2U'],
                                       'positions' : ['']},
                     'nm5se2U_to_mnm5se2U' : {'upstream_rxns' : ['cmnm5se2U_to_nm5se2U',  'se2U_to_nm5se2U' ,'nm5s2U_to_nm5se2U'],
                                       'positions' : ['']},
                     'mnm5s2U_to_mnm5se2U' : {'upstream_rxns' : ['nm5s2U_to_mnm5s2U','mnm5U_to_mnm5s2U'],
                                       'positions' : ['']},
                     'mnm5U_to_mnm5s2U' : {'upstream_rxns' : ['nm5U_to_mnm5U'],
                                       'positions' : ['']},
                     'nm5s2U_to_nm5se2U' : {'upstream_rxns' : ['s2U_to_nm5s2U','cmnm5s2U_to_nm5s2U'],
                                       'positions' : ['']},
                     'nm5s2U_to_mnm5s2U' : {'upstream_rxns' : ['s2U_to_nm5s2U','cmnm5s2U_to_nm5s2U'],
                                       'positions' : ['']},
                     'se2U_to_nm5se2U' : {'upstream_rxns' : ['s2U_to_se2U'],
                                       'positions' : ['']},
                     'cmnm5U_to_nm5U' : {'upstream_rxns' : ['U_to_cmnm5U'],
                                       'positions' : ['']},
                     'cmnm5U_to_cmnm5Um' : {'upstream_rxns' : ['U_to_cmnm5U'],
                                       'positions' : ['']},
                     'Um_to_cmnm5Um' : {'upstream_rxns' : ['U_to_Um'],
                                       'positions' : ['']},
                     'nm5U_to_mnm5U' : {'upstream_rxns' : ['U_to_nm5U', 'cmnm5U_to_nm5U'],
                                       'positions' : ['']},
                     'ho5U_to_cmo5U' : {'upstream_rxns' : ['U_to_ho5U'],
                                       'positions' : ['']}
                     
                     }
                     
