

trna_modification = {'Cm_path_1_at_32': {'carriers': {},
  'machines': ['TrmJ_dim'],
  'metabolites': {'ahcys_c': 1, 'amet_c': -1, 'h_c': 1}},
 'Cm_path_2_at_34': {'carriers': {},
  'machines': ['trmL_dim'],
  'metabolites': {'ahcys_c': 1, 'amet_c': -1, 'h_c': 1}},
 'DDusA_path_3_at_20': {'carriers': {},
  'machines': ['DusA_mono'],
  'metabolites': {'h_c': -1, 'nadp_c': 1, 'nadph_c': -1}},
 'DDusgen_path_1_at_20A': {'carriers': {},
  'machines': ['generic_Dus'],
  'metabolites': {'h_c': -1, 'nadp_c': 1, 'nadph_c': -1}},
 'DDusgen_path_2_at_17': {'carriers': {},
  'machines': ['generic_Dus'],
  'metabolites': {'h_c': -1, 'nadp_c': 1, 'nadph_c': -1}},
 'DDusgen_path_3_at_20': {'carriers': {},
  'machines': ['generic_Dus'],
  'metabolites': {'h_c': -1, 'nadp_c': 1, 'nadph_c': -1}},
 'Gm_path_1_at_18': {'carriers': {},
  'machines': ['TrmH_dim'],
  'metabolites': {'ahcys_c': 1, 'amet_c': -1, 'h_c': 1}},
 'I_path_1_at_34': {'carriers': {},
  'machines': ['TadA_dim_mod_2:zn2'],
  'metabolites': {'h2o_c': -1, 'h_c': -1, 'nh4_c': 1}},
 'QtRNA_path_1_at_34': {'carriers': {},
  'machines': ['Tgt_hexa_mod_6:zn2', 'QueA_mono', 'QueG_mono_mod_adocbl'],
  'metabolites': {'ade_c': 1,
   'amet_c': -1,
   'gua_c': 1,
   'h2o_c': 1,
   'h_c': 1,
   'met__L_c': 1,
   'preq1_c': -1}},
 'Um_path_1_at_32': {'carriers': {},
  'machines': ['TrmJ_dim'],
  'metabolites': {'ahcys_c': 1, 'amet_c': -1, 'h_c': 1}},
 'Y_path_1_at_32': {'carriers': {},
  'machines': ['RluA_mono'],
  'metabolites': {}},
 'Y_path_2_at_65': {'carriers': {},
  'machines': ['YqcB_mono'],
  'metabolites': {}},
 'Y_path_3_at_38': {'carriers': {},
  'machines': ['TruA_dim'],
  'metabolites': {}},
 'Y_path_4_at_39': {'carriers': {},
  'machines': ['TruA_dim'],
  'metabolites': {}},
 'Y_path_5_at_40': {'carriers': {},
  'machines': ['TruA_dim'],
  'metabolites': {}},
 'Y_path_6_at_13': {'carriers': {},
  'machines': ['TruD_mono'],
  'metabolites': {}},
 'Y_path_7_at_55': {'carriers': {},
  'machines': ['TruB_mono'],
  'metabolites': {}},
 'ac4C_path_1_at_34': {'carriers': {},
  'machines': ['TmcA_mono'],
  'metabolites': {'accoa_c': -1,
   'adp_c': 1,
   'atp_c': -1,
   'coa_c': 1,
   'h2o_c': -1,
   'h_c': 1,
   'pi_c': 1}},
 'acp3U_path_1_at_47': {'carriers': {},
  'machines': [],
  'metabolites': {'5mta_c': 1, 'amet_c': -1, 'h_c': 1}},
 'cmnm5Um_path_2_at_34': {'carriers': {},
  'machines': ['MnmEG_cplx_mod_fad_mod_2:k', 'trmL_dim'],
  'metabolites': {'ahcys_c': 1,
   'amet_c': -1,
   'dhf_c': 1,
   'gdp_c': 1,
   'gly_c': -1,
   'gtp_c': -1,
   'h2o_c': -1,
   'h_c': 3,
   'mlthf_c': -1,
   'pi_c': 1}},
 'cmnm5se2U_path_2_at_34': {'carriers': {'IscS_mod_2:pydx5p': 1,
   'IscS_mod_2:pydx5p_mod_1:SH': -1,
   'trdox_c': 1,
   'trdrd_c': -1},
  'machines': ['MnmEG_cplx_mod_fad_mod_2:k',
   'YhhP_mono',
   'YccK_mono',
   'YbbB_dim',
   'YheLMN_cplx',
   'TrmU_mono'],
  'metabolites': {'H2O3PS_c': 1,
   'amp_c': 1,
   'atp_c': -1,
   'dhf_c': 1,
   'gdp_c': 1,
   'gly_c': -1,
   'gtp_c': -1,
   'h2o_c': -1,
   'h_c': 3,
   'mlthf_c': -1,
   'pi_c': 1,
   'ppi_c': 1,
   'selnp_c': -1}},
 'cmo5U_path_1_at_34': {'carriers': {},
  'machines': ['YecP_mono'],
  'metabolites': {'ahcys_c': 1, 'amet_c': -1, 'h_c': 1}},
 'ct6A_path_1_at_37': {'carriers': {},
  'machines': ['TcdA_dim', 'TsaBCDE'],
  'metabolites': {'adp_c': 1,
   'amp_c': 1,
   'atp_c': -2,
   'h2o_c': 1,
   'h_c': 2,
   'hco3_c': -1,
   'pi_c': 1,
   'ppi_c': 1,
   'thr__L_c': -1}},
 'ges2U_path_1_at_34': {'carriers': {'IscS_mod_2:pydx5p': 1,
   'IscS_mod_2:pydx5p_mod_1:SH': -1,
   'trdox_c': 1,
   'trdrd_c': -1},
  'machines': ['YheLMN_cplx',
   'YbbB_dim',
   'YccK_mono',
   'YhhP_mono',
   'TrmU_mono'],
  'metabolites': {'amp_c': 1, 'atp_c': -1, 'grdp_c': 1, 'h_c': 1, 'ppi_c': 0}},
 'gluQtRNA_path_1_at_34': {'carriers': {},
  'machines': ['Tgt_hexa_mod_6:zn2',
   'YadB_mono',
   'QueA_mono',
   'QueG_mono_mod_adocbl'],
  'metabolites': {'ade_c': 1,
   'amet_c': -1,
   'amp_c': 1,
   'atp_c': 1,
   'glu__L_c': -1,
   'gua_c': 1,
   'h2o_c': 1,
   'h_c': 3,
   'met__L_c': 1,
   'ppi_c': 1,
   'preq1_c': -1}},
 'i6A_path_1_at_37': {'carriers': {},
  'machines': ['MiaA_dim_mod_2:mg2'],
  'metabolites': {'dmpp_c': 1, 'ppi_c': 1}},
 'k2C_path_1_at_34': {'carriers': {},
  'machines': ['TilS_mono'],
  'metabolites': {'amp_c': 1,
   'atp_c': -1,
   'h_c': 2,
   'lys__L_c': -1,
   'ppi_c': 1}},
 'm1G_path_1_at_37': {'carriers': {},
  'machines': ['TrmD_dim'],
  'metabolites': {'ahcys_c': 1, 'amet_c': -1, 'h_c': 1}},
 'm2A_path_1_at_37': {'carriers': {},
  'machines': ['RlmN_mono_mod_1:4fe4s'],
  'metabolites': {'ahcys_c': 1, 'amet_c': -2, 'dad__5_c': 1, 'met__L_c': 1}},
 'm5U_path_1_at_54': {'carriers': {},
  'machines': ['TrmA_mono'],
  'metabolites': {'ahcys_c': 1, 'amet_c': -1, 'h_c': 1}},
 'm6A_path_1_at_37': {'carriers': {},
  'machines': ['YfiC_mono'],
  'metabolites': {'ahcys_c': 1, 'amet_c': -1, 'h_c': 1}},
 'm6t6A_path_1_at_37': {'carriers': {},
  'machines': ['EG11503_MONOMER', 'TsaBCDE'],
  'metabolites': {'ahcys_c': 1,
   'amet_c': -1,
   'amp_c': 1,
   'atp_c': -1,
   'h2o_c': 1,
   'h_c': 2,
   'hco3_c': -1,
   'ppi_c': 1,
   'thr__L_c': -1}},
 'm7G_path_1_at_46': {'carriers': {},
  'machines': ['YggH_mono'],
  'metabolites': {'ahcys_c': 1, 'amet_c': -1}},
 'mnm5U_path_1_at_34': {'carriers': {},
  'machines': ['MnmEG_cplx_mod_fad_mod_2:k',
   'MnmC_mono_mod_fad',
   'MnmC_mono_mod_fad'],
  'metabolites': {'ahcys_c': 1,
   'amet_c': -1,
   'dhf_c': 1,
   'gdp_c': 1,
   'glx_c': 1,
   'gly_c': -1,
   'gtp_c': -1,
   'h2o_c': -1,
   'h_c': 3,
   'mlthf_c': -1,
   'pi_c': 1}},
 'mnm5U_path_2_at_34': {'carriers': {},
  'machines': ['MnmEG_cplx_mod_fad_mod_2:k', 'MnmC_mono_mod_fad'],
  'metabolites': {'ahcys_c': 1,
   'amet_c': -1,
   'dhf_c': 1,
   'gdp_c': 1,
   'gtp_c': -1,
   'h2o_c': -1,
   'h_c': 1,
   'mlthf_c': -1,
   'nh4_c': -1,
   'pi_c': 1}},
 'mnm5ges2U_path_4_at_34': {'carriers': {'IscS_mod_2:pydx5p': 1,
   'IscS_mod_2:pydx5p_mod_1:SH': -1,
   'trdox_c': 1,
   'trdrd_c': -1},
  'machines': ['MnmC_mono_mod_fad',
   'MnmC_mono_mod_fad',
   'MnmEG_cplx_mod_fad_mod_2:k',
   'YhhP_mono',
   'YccK_mono',
   'YbbB_dim',
   'YheLMN_cplx',
   'TrmU_mono'],
  'metabolites': {'ahcys_c': 1,
   'amet_c': -1,
   'amp_c': 1,
   'atp_c': -1,
   'dhf_c': 1,
   'gdp_c': 1,
   'glx_c': 1,
   'gly_c': -1,
   'grdp_c': 1,
   'gtp_c': -1,
   'h2o_c': -1,
   'h_c': 4,
   'mlthf_c': -1,
   'pi_c': 1,
   'ppi_c': 0}},
 'mnm5ges2U_path_5_at_34': {'carriers': {'IscS_mod_2:pydx5p': 1,
   'IscS_mod_2:pydx5p_mod_1:SH': -1,
   'trdox_c': 1,
   'trdrd_c': -1},
  'machines': ['MnmC_mono_mod_fad',
   'MnmEG_cplx_mod_fad_mod_2:k',
   'YhhP_mono',
   'YccK_mono',
   'YbbB_dim',
   'YheLMN_cplx',
   'TrmU_mono'],
  'metabolites': {'ahcys_c': 1,
   'amet_c': -1,
   'amp_c': 1,
   'atp_c': -1,
   'dhf_c': 1,
   'gdp_c': 1,
   'grdp_c': 1,
   'gtp_c': -1,
   'h2o_c': -1,
   'h_c': 2,
   'mlthf_c': -1,
   'nh4_c': -1,
   'pi_c': 1,
   'ppi_c': 0}},
 'mnm5se2U_path_6_at_34': {'carriers': {'IscS_mod_2:pydx5p': 1,
   'IscS_mod_2:pydx5p_mod_1:SH': -1,
   'trdox_c': 1,
   'trdrd_c': -1},
  'machines': ['MnmC_mono_mod_fad',
   'MnmC_mono_mod_fad',
   'MnmEG_cplx_mod_fad_mod_2:k',
   'YhhP_mono',
   'YccK_mono',
   'YbbB_dim',
   'YheLMN_cplx',
   'TrmU_mono'],
  'metabolites': {'H2O3PS_c': 1,
   'ahcys_c': 1,
   'amet_c': -1,
   'amp_c': 1,
   'atp_c': -1,
   'dhf_c': 1,
   'gdp_c': 1,
   'glx_c': 1,
   'gly_c': -1,
   'gtp_c': -1,
   'h2o_c': -1,
   'h_c': 4,
   'mlthf_c': -1,
   'pi_c': 1,
   'ppi_c': 1,
   'selnp_c': -1}},
 'mnm5se2U_path_8_at_34': {'carriers': {'IscS_mod_2:pydx5p': 1,
   'IscS_mod_2:pydx5p_mod_1:SH': -1,
   'trdox_c': 1,
   'trdrd_c': -1},
  'machines': ['MnmC_mono_mod_fad',
   'MnmEG_cplx_mod_fad_mod_2:k',
   'YhhP_mono',
   'YccK_mono',
   'YbbB_dim',
   'YheLMN_cplx',
   'TrmU_mono'],
  'metabolites': {'H2O3PS_c': 1,
   'ahcys_c': 1,
   'amet_c': -1,
   'amp_c': 1,
   'atp_c': -1,
   'dhf_c': 1,
   'gdp_c': 1,
   'gtp_c': -1,
   'h2o_c': -1,
   'h_c': 2,
   'mlthf_c': -1,
   'nh4_c': -1,
   'pi_c': 1,
   'ppi_c': 1,
   'selnp_c': -1}},
 'mo5U_path_1_at_34': {'carriers': {},
  'machines': ['YecP_mono'],
  'metabolites': {}},
 'ms2i6A_path_1_at_37': {'carriers': {'IscS_mod_2:pydx5p': 1,
   'IscS_mod_2:pydx5p_mod_1:SH': -1,
   'fldox_c': 1,
   'fldrd_c': -1},
  'machines': ['MiaB_mono_mod_1:4fe4s', 'MiaA_dim_mod_2:mg2'],
  'metabolites': {'ahcys_c': 1,
   'amet_c': -2,
   'dad__5_c': 1,
   'dmpp_c': 1,
   'h_c': 2,
   'met__L_c': 1,
   'ppi_c': 1}},
 's2C_path_1_at_32': {'carriers': {'IscS_mod_2:pydx5p': 1,
   'IscS_mod_2:pydx5p_mod_1:SH': -1,
   'trdox_c': 1,
   'trdrd_c': -1},
  'machines': ['YdaO_mono'],
  'metabolites': {'cys__L_e': -1, 'ser__L_c': 1}},
 's4U_path_1_at_8': {'carriers': {'IscS_mod_2:pydx5p': 1,
   'IscS_mod_2:pydx5p_mod_1:SH': -1,
   'trdox_c': 1,
   'trdrd_c': -1},
  'machines': ['ThiI_mono'],
  'metabolites': {'amp_c': 1, 'atp_c': -1, 'h_c': 1, 'ppi_c': 1}},
 't6A_path_1_at_37': {'carriers': {},
  'machines': ['TsaBCDE'],
  'metabolites': {'amp_c': 1,
   'atp_c': -1,
   'h2o_c': 1,
   'h_c': 1,
   'hco3_c': -1,
   'ppi_c': 1,
   'thr__L_c': -1}}}